; Script generated by Gemini CLI
; Professional Installer with System Audit Wizard

#define MyAppName "Koperasi Brimob"
#define MyAppVersion "1.7"
#define MyAppPublisher "Emergent"
#define MyAppURL "https://www.example.com/"
#define MyAppExeName "KoperasiBrimob.exe"

[Setup]
AppId={{C62B6D4F-8F32-4161-9C55-789012345678}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
DisableProgramGroupPage=yes
PrivilegesRequired=admin
OutputDir=.
OutputBaseFilename=KoperasiBrimob_Setup_v{#MyAppVersion}
Compression=lzma
SolidCompression=yes
WizardStyle=modern
MinVersion=6.1

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "dist\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "diagnostic_check.bat"; DestDir: "{app}"; Flags: ignoreversion

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

[Code]
var
  AuditPage: TWizardPage;
  StatusLabel: TNewStaticText;
  DetailLabel: TNewStaticText;
  RecheckButton: TNewButton;
  IsSystemReady: Boolean;

// Check if a specific KB is installed via PowerShell
function CheckKB(KBID: String): Boolean;
var
  ResultCode: Integer;
begin
  if Exec('powershell.exe', '-NoProfile -ExecutionPolicy Bypass -Command "if (Get-HotFix -Id ' + KBID + ' -ErrorAction SilentlyContinue) { exit 0 } else { exit 1 }"', '', SW_HIDE, ewWaitUntilTerminated, ResultCode) then
    Result := (ResultCode = 0)
  else
    Result := False;
end;

function IsWin7: Boolean;
var
  Version: TWindowsVersion;
begin
  GetWindowsVersionEx(Version);
  Result := (Version.Major = 6) and (Version.Minor = 1);
end;

function IsSP1: Boolean;
var
  Version: TWindowsVersion;
begin
  GetWindowsVersionEx(Version);
  Result := (Version.ServicePackMajor >= 1);
end;

function OnDownloadProgress(const Url, FileName: String; const BytesDownloaded, BytesTotal: Int64): Boolean;
begin
  if BytesTotal > 0 then
    WizardForm.StatusLabel.Caption := Format('Downloading update... %d%%', [Round((BytesDownloaded / BytesTotal) * 100)])
  else
    WizardForm.StatusLabel.Caption := 'Downloading update...';
  Result := True;
end;

function InstallKB(KBID, Url, FileName: String): Boolean;
var
  ResultCode: Integer;
  Path: String;
begin
  WizardForm.StatusLabel.Caption := 'Downloading ' + KBID + '...';
  try
    DownloadTemporaryFile(Url, FileName, '', @OnDownloadProgress);
    Path := ExpandConstant('{tmp}\' + FileName);
    
    WizardForm.StatusLabel.Caption := 'Installing ' + KBID + '...';
    // Run wusa.exe. 
    // Exit Code 3010 means restart required. 0 means success. 2359302 means already installed.
    if Exec('wusa.exe', '"' + Path + '" /quiet /norestart', '', SW_SHOW, ewWaitUntilTerminated, ResultCode) then
    begin
      if (ResultCode = 0) or (ResultCode = 3010) then
      begin
        Result := True;
        if ResultCode = 3010 then
        begin
          MsgBox('Windows requires a restart to complete the installation of ' + KBID + '.' + #13#10 + 
                 'Please restart your computer and run this setup again.', mbInformation, MB_OK);
        end;
      end
      else if ResultCode = 2359302 then // Already installed
      begin
        Result := True;
      end
      else
      begin
        MsgBox('Failed to install ' + KBID + '. Error code: ' + IntToStr(ResultCode), mbError, MB_OK);
        Result := False;
      end;
    end
    else
    begin
      MsgBox('Failed to execute installer for ' + KBID + '.', mbError, MB_OK);
      Result := False;
    end;
  except
    MsgBox('Failed to download ' + KBID + '.' + #13#10 + GetExceptionMessage, mbError, MB_OK);
    Result := False;
  end;
end;

procedure PerformAudit;
var
  Missing: String;
  NeedsKB2999226: Boolean;
begin
  StatusLabel.Caption := 'Scanning system for compatibility...';
  DetailLabel.Caption := '';
  RecheckButton.Caption := 'Re-scan';
  RecheckButton.Tag := 0; // 0 = Rescan, 1 = Install Updates
  WizardForm.NextButton.Enabled := False;
  IsSystemReady := True;
  Missing := '';
  NeedsKB2999226 := False;

  if IsWin7 then
  begin
    if not IsSP1 then
    begin
      Missing := Missing + '• Service Pack 1' + #13#10;
      IsSystemReady := False;
    end;

    // We focus on KB2999226 as requested, but keep others in check if needed.
    // However, the user specifically asked for KB2999226 download logic.
    if not CheckKB('KB2999226') then
    begin
      Missing := Missing + '• KB2999226 (Universal C Runtime)' + #13#10;
      IsSystemReady := False;
      NeedsKB2999226 := True;
    end;
    
    // Optional: Add other KBs checks here
  end;

  if IsSystemReady then
  begin
    StatusLabel.Caption := 'Result: SYSTEM COMPATIBLE';
    StatusLabel.Font.Color := clGreen;
    DetailLabel.Caption := 'All required system components were found.' + #13#10 + 'Click Next to continue.';
    WizardForm.NextButton.Enabled := True;
    RecheckButton.Visible := True;
    RecheckButton.Caption := 'Re-scan';
  end
  else
  begin
    StatusLabel.Caption := 'Result: MISSING REQUIREMENTS';
    StatusLabel.Font.Color := clRed;
    DetailLabel.Caption := 'The following components are missing for Windows 7:' + #13#10 + #13#10 +
                           Missing;
    
    if NeedsKB2999226 then
    begin
       DetailLabel.Caption := DetailLabel.Caption + #13#10 + 'Click "Install Updates" to download and install automatically.';
       RecheckButton.Caption := 'Install Updates';
       RecheckButton.Tag := 1; // Mode 1: Install
    end
    else
    begin
       DetailLabel.Caption := DetailLabel.Caption + #13#10 + 'Please install these updates manually and click "Re-scan".';
    end;

    WizardForm.NextButton.Enabled := False;
  end;
end;

procedure InstallMissingUpdates;
var
  Url: String;
  FileName: String;
begin
  if IsWin64 then
  begin
    Url := 'https://download.microsoft.com/download/1/1/5/11565A9A-EA09-4F0A-A57E-520D5D138140/Windows6.1-KB2999226-x64.msu';
    FileName := 'Windows6.1-KB2999226-x64.msu';
  end
  else
  begin
    Url := 'https://download.microsoft.com/download/4/F/E/4FE73868-5EDD-4B47-8B33-CE1BB7B2B16A/Windows6.1-KB2999226-x86.msu';
    FileName := 'Windows6.1-KB2999226-x86.msu';
  end;

  if InstallKB('KB2999226', Url, FileName) then
  begin
    MsgBox('Update installed successfully. Rescanning...', mbInformation, MB_OK);
    PerformAudit;
  end;
end;

procedure RecheckButtonClick(Sender: TObject);
begin
  if RecheckButton.Tag = 1 then
    InstallMissingUpdates
  else
    PerformAudit;
end;

procedure InitializeWizard;
begin
  AuditPage := CreateCustomPage(wpWelcome, 'System Compatibility Audit', 'Checking if your device is ready for {#MyAppName}.');
  
  StatusLabel := TNewStaticText.Create(AuditPage);
  StatusLabel.Parent := AuditPage.Surface;
  StatusLabel.Left := 0;
  StatusLabel.Top := 10;
  StatusLabel.Width := AuditPage.SurfaceWidth;
  StatusLabel.Font.Size := 10;
  StatusLabel.Font.Style := [fsBold];
  StatusLabel.Caption := 'Initializing scan...';

  DetailLabel := TNewStaticText.Create(AuditPage);
  DetailLabel.Parent := AuditPage.Surface;
  DetailLabel.Left := 0;
  DetailLabel.Top := 40;
  DetailLabel.Width := AuditPage.SurfaceWidth;
  DetailLabel.Height := 120;
  DetailLabel.Caption := '';

  RecheckButton := TNewButton.Create(AuditPage);
  RecheckButton.Parent := AuditPage.Surface;
  RecheckButton.Left := 0;
  RecheckButton.Top := 180;
  RecheckButton.Width := 100;
  RecheckButton.Caption := 'Re-scan';
  RecheckButton.OnClick := @RecheckButtonClick;
end;

procedure CurPageChanged(CurPageID: Integer);
begin
  if CurPageID = AuditPage.ID then
  begin
    PerformAudit;
  end;
end;
